[package]
name = "rs-platform-explorer"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
strum = { version = "0.25.0", features = ["derive"] }
tui-realm-stdlib = "1.3.0"
tuirealm = "1.9.0"
bs58 = "0.5.0"
dpp = { path = "../platform/packages/rs-dpp/", features = ["identity-serialization", "identity-serde-conversion"]}
thiserror = "1.0.49"
serde = "1.0.188"
toml = { version = "0.8.2", features = ["display"] }
dapi-grpc = { path = "../platform/packages/dapi-grpc/", features = ["client"]}
rs-dapi-client = { path = "../platform/packages/rs-dapi-client/"}
tokio = { version = "1.32.0", features = ["full"] }
rs-sdk = { path = "../platform/packages/rs-sdk/"}