[package]
name = "rs-platform-explorer"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
strum = { version = "0.25.0", features = ["derive"] }
tui-realm-stdlib = "1.3.0"
tuirealm = "1.9.0"
