[package]
name = "rs-platform-explorer"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
strum = { version = "0.25.0", features = ["derive"] }
tui-realm-stdlib = "1.3.0"
tuirealm = "1.9.0"
rs-sdk = { git = "https://github.com/dashpay/platform", branch = "rs-sdk/read-document-identity-contract" }
rs-dapi-client = { git = "https://github.com/dashpay/platform", branch = "rs-sdk/read-document-identity-contract" }
bs58 = "0.5.0"
